# ci:target:x86:64 is going to trigger CI target check jobs for x86/64 target

name: Build check target specified in labels
on:
  workflow_call:
    inputs:
      target:
        type: string
      subtarget:
        type: string

jobs:
  set_target:
    if: startsWith(github.event.label.name, 'ci:target:') || inputs.target != ''
    name: Set target
    runs-on: ubuntu-latest
    outputs:
      target: ${{ steps.set_target.outputs.target }}
      subtarget: ${{ steps.set_target.outputs.subtarget }}

    steps:
      - name: Set target
        id: set_target
        env:
          CI_EVENT_LABEL_NAME: ${{ github.event.label.name }}
        run: |
          if [ -n "${{ inputs.target}}" ]; then
            target="${{ inputs.target }}"
          else
            target=$(echo "$CI_EVENT_LABEL_NAME" | sed -n 's/.*:\(.*\):\(.*\)$/\1/p')
          fi

          if [ -n "${{ inputs.subtarget}}" ]; then
            subtarget="${{ inputs.subtarget }}"
          else
            subtarget=$(echo "$CI_EVENT_LABEL_NAME" | sed -n 's/.*:\(.*\):\(.*\)$/\2/p')
          fi

          echo "Setting target as $target, subtarget as $subtarget"
          {
            echo "target=$target"
            echo "subtarget=$subtarget"
          } >> "$GITHUB_OUTPUT"

  build_target:
    name: Build target
    needs: set_target
    permissions:
      contents: read
      packages: read
      actions: write
    uses: ./.github/workflows/reusable_build.yml
    with:
      container_name: toolchain
      target: ${{ needs.set_target.outputs.target }}
      subtarget: ${{ needs.set_target.outputs.subtarget }}
      build_full: true
      build_all_kmods: true
      build_all_boards: true
      build_all_modules: true
