name: Upload File to S3

on:
  workflow_call:
    secrets:
      s3_endpoint:
      s3_bucket:
      s3_access_key:
      s3_secret_key:
    inputs:
      download_id:
        required: true
        type: string
      filename:
        required: true
        type: string

jobs:
  upload-file-in-s3:
    name: Upload file in S3
    runs-on: ubuntu-latest

    steps:
      - name: Download file
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.download_id }}

      - name: Upload file to s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.s3_access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.s3_secret_key }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_REQUEST_CHECKSUM_CALCULATION: when_required
          AWS_RESPONSE_CHECKSUM_VALIDATION: when_required
          S3_ENDPOINT: ${{ secrets.s3_endpoint }}
          S3_BUCKET: ${{ secrets.s3_bucket }}
          FILENAME: ${{ inputs.filename }}
        run: |
          aws configure set default.s3.addressing_style path
          aws s3 cp "$FILENAME" "s3://$S3_BUCKET/" --endpoint-url "$S3_ENDPOINT" --no-progress
